### ISSUE TITLE
Change the way we load dependencies

### ISSUE THREAD

**Issue by iainduncani** [WASdev/tool.accelerate.core#100]
Currently there is a lot of duplication and room for confusion in the way dependencies are loaded.  You have to have a POM file, register the POM through Gradle and then list the dependency in the tech type endpoint.  The endpoint allows for multiple dependencies with different group IDs for a single scope to be returned. However, the DependencyHandler code only allows for a single dependency per scope per tech type as these are stored in a map keyed by the tech type. Furthermore, the code to produce the pom/gradle build file then ignore the group ID and assume it is named after the tech type (which is just as well as spring boot web returns the wrong group ID!).  There is also duplication across all the tech types as they all have nearly identical dependencies that only vary based on the group id and version, the former of which is generated by the core project anyway.

Instead, I think that there should be a single tech type endpoint class for handling dependencies.  I think it should return a different set of JSON such as:

{
  "hasProvided": true,
  "hasCompile": false,
  "hasRuntime": true,
  "version":  0.0.2
}

All of this information is known in the gradle build file at the moment so this could generate a properties file in each tech type WAR that is read by the common class to produce this JSON.  The core projects would not need to alter that much to handle this although would need to move the artifact IDs up to those projects.

**Comment by katheris** [comment]
Closing as invalid since we have changed the way dependencies are added.
