### ISSUE TITLE
Add GitHub integration

### ISSUE THREAD

**Issue by iainduncani** [WASdev/tool.accelerate.core#103]
Add ability to create a repository on git hub containing the generated project

**Comment by iainduncani** [comment]
What I've learnt so far...
In the GitHub API you can't create branches and commits for a bunch of changes but you can do them a file at a time via the contents API (this does one commit per file so they'd end up with lots of commits but meh):
https://developer.github.com/v3/repos/contents/
There is a Java client for the API supplied by Eclipse:
https://github.com/eclipse/egit-github/tree/f0d112d78f1d4b87240abfe1aebe773125c843b2/org.eclipse.egit.github.core
It's easy to include as a Gradle dependency:
compile group: 'org.eclipse.mylyn.github', name: 'org.eclipse.egit.github.core', version: '2.1.5'
It looks easy to use and takes out the faff of doing http url connections etc.  Sadly though the ContentsService doesn't include something to create new contents but this is easy to add:
`import org.eclipse.egit.github.core.Repository;

import java.io.IOException;

import static org.eclipse.egit.github.core.client.IGitHubConstants.SEGMENT_CONTENTS;
import static org.eclipse.egit.github.core.client.IGitHubConstants.SEGMENT_REPOS;

public class ContentsService extends org.eclipse.egit.github.core.service.ContentsService {

    public RepositoryContentsUpdateResponse createContents(Repository repository, RepositoryContentsInput contents) throws IOException {
        String id = getId(repository);

        StringBuilder uri = new StringBuilder(SEGMENT_REPOS);
        uri.append('/').append(id);
        uri.append(SEGMENT_CONTENTS);
        uri.append('/').append(contents.getPath());
        System.out.println(uri.toString());
        return client.put(uri.toString(), contents,
                RepositoryContentsUpdateResponse.class);
    }
}
`
It needs a couple of contents classes to go with it:
`
import org.eclipse.egit.github.core.Commit;
import org.eclipse.egit.github.core.RepositoryContents;

import java.io.Serializable;

public class RepositoryContentsUpdateResponse implements Serializable {

    private static final long serialVersionUID = -7656647424869410604L;
    private RepositoryContents content;
    private Commit commit;

    public RepositoryContents getContent() {
        return content;
    }

    public void setContent(RepositoryContents content) {
        this.content = content;
    }

    public Commit getCommit() {
        return commit;
    }

    public void setCommit(Commit commit) {
        this.commit = commit;
    }

}
`
and
`
import java.io.Serializable;

public class RepositoryContentsInput implements Serializable {

    private static final long serialVersionUID = -7398795353339908029L;
    private String content;
    private String path;
    private String message;

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }
}
`
Putting this all together you can create a repo and add contents by:
`
       RepositoryService service = new RepositoryService();
        service.getClient().setCredentials("<user_id>", "<password>");
        Repository testRepo = new Repository();
        testRepo.setName("testRepoCreation");
//        testRepo = service.getRepository("iainduncani", "testRepoCreation");
        testRepo = service.createRepository(testRepo);
        ContentsService contentsService = new ContentsService();
        contentsService.getClient().setCredentials("<user_id>", "<password>");
        RepositoryContentsInput contents = new RepositoryContentsInput();
        contents.setPath("wibble.txt");
        contents.setMessage("Initial commit");
        contents.setContent(Base64.getEncoder().encodeToString("wibble".getBytes()));
        contentsService.createContents(testRepo, contents);
`

**Comment by iainduncani** [comment]
Looks like JGit may be a better approach as you can then do everything in a single commit

https://git-scm.com/book/be/v2/Embedding-Git-in-your-Applications-JGit

**Comment by iainduncani** [comment]
So JGit will do what we want.  It is just a Java wrapper around standard Git commands so you can do whatever you would do from the Git CLI but in Java.  Two things to note:

1. There is no standard for creating a remote repository using Git commands so you have to do this via a vendor provided mechanism so we would still need to use eGit (above) as well to actually create the repository in GitHub
2. You have to work with files on the file system rather than in memory. Therefore we will need to write all the files to a temporary directory and then push it

The code to do this is as follows:

```
import org.eclipse.egit.github.core.Repository;
import org.eclipse.egit.github.core.service.RepositoryService;
import org.eclipse.jgit.api.CloneCommand;
import org.eclipse.jgit.api.Git;
import org.eclipse.jgit.api.PushCommand;
import org.eclipse.jgit.api.TransportCommand;
import org.eclipse.jgit.api.errors.GitAPIException;
import org.eclipse.jgit.transport.UsernamePasswordCredentialsProvider;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;

public class PlayJGit {

    public static void main(String[] args) throws GitAPIException, IOException {
        RepositoryService service = new RepositoryService();
        service.getClient().setCredentials("<user>", "<password>");
        Repository testRepo = new Repository();
        testRepo.setName("testRepoCreation");
        service.createRepository(testRepo);

        File dir = new File("C:\\temp\\jgit\\testRepoCreation");
        CloneCommand cloneCommand = Git.cloneRepository()
                .setURI("https://github.com/iainduncani/testRepoCreation")
                .setDirectory(dir);
        addAuth(cloneCommand);
        Git git = cloneCommand.call();
        Files.write(new File(dir, "readme.txt").toPath(), "hello, world!".getBytes());
        git.add().addFilepattern(".").call();
        git.commit().setMessage("Initial commit").call();
        PushCommand pushCommand = git.push();
        addAuth(pushCommand);
        pushCommand.call();
    }

    private static void addAuth(TransportCommand command) {
        command.setCredentialsProvider(new UsernamePasswordCredentialsProvider("<user>", "<password>"));
    }

}
```

**Comment by katheris** [comment]
Completed in https://github.com/WASdev/tool.accelerate.core/pull/148
