### ISSUE TITLE
Enable unit tests

### ISSUE THREAD

**Issue by katheris** [WASdev/tool.accelerate.core#106]
At the moment the unit tests do not appear to be running.

**Comment by iainduncani** [comment]
Really? In what environment? They have run locally and on the build for the latest PR:

https://travis-ci.org/WASdev/tool.accelerate.core/builds/181680957

`:liberty-starter-application:test`

**Comment by katheris** [comment]
Hmm, weird it doesn't run locally on mine! The tech type unit tests do, but the liberty-starter-application ones don't. It doesn't appear in the logs and the results don't appear in the build folder.

**Comment by iainduncani** [comment]
That is weird, what command do you run? I just tested mine locally doing:
`gradle clean build`
(Just noticed I don't actually use the gradlew) and that ran them for me.  Do you now even get an up to date check done on them? One thing to note that is slightly unexpected is it runs after the FVT for me.

**Comment by katheris** [comment]
I ran ./gradlew clean build and once I added it to the depends on list it ran after FVT for me as well. Check depends on fvt and test but not in a particular order

**Comment by iainduncani** [comment]
Are you saying that you had to explicitly add `check.dependsOn 'test'` to get it to run? That should come from having the Java plugin applied

**Comment by katheris** [comment]
Closing as this issue is resolved.
