### ISSUE TITLE
Update Gradle to accept feature install licenses by default

### ISSUE THREAD

**Issue by katheris** [WASdev/tool.accelerate.core#108]
Update Gradle to accept feature install licenses by default

**Comment by iainduncani** [comment]
Also echo a comment when running the build similar to maven:

                                <echo message="By building this project you agree that you have had the opportunity to review the Apache Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0) and Liberty (https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/license/base_ilan/ilan/16.0.0.3/lafiles/en.html) licenses and you agree to be bound by their terms. If you disagree, abort the build."/>
