### ISSUE TITLE
wlp starters for Spring boot and Spring Cloud based dependencies.

### ISSUE THREAD

**Issue by bsridhar123** [WASdev/tool.accelerate.core#145]
Hi,

I see the starter project for spring boot based liberty project uses,
3 types of artifacts for **"net.wasdev.wlp.starters.springbootweb"** with scope **provided,compile and runtime.**

Why cannot we directly refer the spring boot dependency in pom.xml. Why do we have 3 different artifacts for spring boot.

Also, what is the version of the spring boot on which this artifact is based upon.

Is it possible to upgrade to the latest version of **Spring Boot which is 1.4.3.** If so, how.

Also, I want to use Spring Cloud netflix dependencies like eureka and zuul for service registry and reverse proxy.
I want to understand how I can add those dependencies to the pom.xml. With liberty I see they are somewhat different from those from spring framework.

Should I be creating custom artifacts (provided,compile and runtime)  for them similar to springbootweb.

Is there any document you can point me to  which I can refer to on how these custom artifacts can be created , if we want to add spring framework dependencies to the pom.xml.

I have currently having difficulties in referring the other dependencies like those of Spring cloud in the pom.xml.

Thanks,
Sri

**Comment by katheris** [comment]
Hi Sri,

Thanks for your feedback, we are constantly working to improve the usability of this webpage so this feedback is great. The provided dependency provides the api's required by Liberty to run the app and the runtime dependency is used to configure Liberty. Finally the compile dependency provides the Spring dependencies that are not provided by Liberty and therefore need to be included in the application.

You can see what dependencies are being added by looking at the contents of the repository files here:

https://github.com/WASdev/tool.accelerate.core/blob/master/starter-microservice-springboot-web/repository/0.0.3/provided-pom.xml

https://github.com/WASdev/tool.accelerate.core/blob/master/starter-microservice-springboot-web/repository/0.0.3/compile-pom.xml
You can add additional dependencies as you would to any other pom.xml file.

**Comment by katheris** [comment]
Closing this as we have now updated the pom.xml to list the dependencies explicitly.
