### ISSUE TITLE
default server.xml in MicroProfile package missing closing <feature> tag

### ISSUE THREAD

**Issue by lauracowen** [WASdev/tool.accelerate.core#154]
The default server.xml contains these lines:

    

The closing `<feature>` tag is missing it's `/` so if the user just uncomments the entries and types in a feature name, they get errors (but it's really hard to notice what's why...).

**Comment by katheris** [comment]
Closing because as of https://github.com/WASdev/tool.accelerate.core/pull/194 we do not include this default server.xml any more.
