### ISSUE TITLE
Test dependency now invalid

### ISSUE THREAD

**Issue by BillyD73** [WASdev/tool.accelerate.core#179]
<dependency>
	<groupId>org.apache.cxf</groupId>
	<artifactId>cxf-rt-rs-client</artifactId>
	<version>3.1.1</version>
	<scope>test</scope>
</dependency>

This dependency now creates an invalid error as follows:

[WARNING] The POM for org.apache.cxf:cxf-rt-rs-client:jar:3.1.1 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details

Which invalidates these classes

import javax.ws.rs.client.Client;
import javax.ws.rs.client.ClientBuilder;
import javax.ws.rs.client.Invocation;
import javax.ws.rs.client.WebTarget;
import javax.ws.rs.core.Response;

import org.apache.cxf.helpers.IOUtils;

**Comment by BillyD73** [comment]
Found that this seems to only occur in Eclipse (worked fine with command line). 

Work-around: 

- run mvn in command line
- update pom.xml to use version 3.1.11

**Comment by katheris** [comment]
Closing as the pom.xml has been updated to use version 3.1.11 of org.apache.cxf:cxf-rt-rs-client
