### ISSUE TITLE
Typo in generated pom.xml

### ISSUE THREAD

**Issue by lauracowen** [WASdev/tool.accelerate.core#196]
1. Create a Spring Boot project (it may happen to all types of project but this is the one I found it in).
2. Look in the pom.xml for the following section:

```xml
<executions>
                    <execution>
                        <id>intall-liberty</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>install-server</goal>
                        </goals>
                    </execution>
```
The `<id>` line should say `install-liberty` not `intall-liberty`.

**Comment by katheris** [comment]
Closing as this is now fixed.
