### ISSUE TITLE
Update app accelerator to use the version 2 of the Liberty Maven plug-in

### ISSUE THREAD

**Issue by cthigh** [WASdev/tool.accelerate.core#197]
App accelerator currently uses v1.0 of liberty-maven-plugin. 

In general check the lifecycle and take advantage of the new goals in version 2.0 such as test-start-server and test-stop-server.  

Also, the create-server goal is not explicitly added to the pom.xml in all cases. In a sample, when the `install-feature` goal was added to the `prepare-package` phase and `create-server` was not also bound to `prepare-package`, we got the error `CWWKF1259E: Unable to obtain the following assets: defaultServer.` because the server had not yet been created.

**Comment by cherylking** [comment]
Liberty app accelerator was taken down end of March. We will not be making further changes.
