### ISSUE TITLE
URL on landing page doesn't reflect project name (and wlp path isn't correct either).

### ISSUE THREAD

**Issue by holly-cummins** [WASdev/tool.accelerate.core#200]
Minor niggle: No matter what project name I choose at, I still see a bar saying 

Access your application at:

http://localhost:9080/myLibertyApp/

on the right-hand side. 

Similarly, if I choose a gradle project, the wlp path is still shown as 
`target/wlp/usr/servers/LibertyProjectServer
`when my actual path is 
     `build/wlp/usr/servers/defaultServer/`

**Comment by patricktiu** [comment]
application url is still not fixed if choosing bluemix deployment

**Comment by patricktiu** [comment]
resolved by PR #204
