### ISSUE TITLE
Update app accelerator template to use Liberty 18.0.0.1

### ISSUE THREAD

**Issue by idlewis** [WASdev/tool.accelerate.core#223]
Liberty 18.0.0.1 has just been released, so the template should be updated to use it.
@patricktiu are you still the right person to do this?

**Comment by cherylking** [comment]
Opened issue https://github.com/ibm-developer/generator-ibm-java-liberty/issues/36 for this, as that is where the change is needed.

**Comment by idlewis** [comment]
@cherylking For the next Liberty release, should I raise an issue directly in the generator-ibm-java-liberty repository to request the template be updated/

**Comment by cherylking** [comment]
The change was merged via https://github.com/ibm-developer/generator-ibm-java-liberty/pull/37.
