### ISSUE TITLE
Liberty App Accelerator website down

### ISSUE THREAD

**Issue by readlearncode** [WASdev/tool.accelerate.core#224]
I went here: [https://liberty-app-accelerator.wasdev.developer.ibm.com/start/](https://liberty-app-accelerator.wasdev.developer.ibm.com/start/) and received the following message: **404 Not Found: Requested route ('liberty-starter.wasdev.developer.ibm.com') does not exist**.

**Comment by cherylking** [comment]
The Liberty app accelerator was taken down intentionally. A static html will be displayed at that address shortly that directs users to alternatives.

**Comment by cherylking** [comment]
The 404 has been replaced with a static html.
