### ISSUE TITLE
Failed to Execute Goal net.wasdev.wlp.maven.plugins:liberty-maven-plugin:1.1:install-apps (default-install-apps) on project myArtifactId-wlpcfg: Use a resource collection to copy directories. ->

### ISSUE THREAD

**Issue by lriv** [WASdev/tool.accelerate.core#43]
Maybe a newbie question!

Trying the Liberty App Accelerator for REST on a mac and am getting stuck.  Suggestions?

[INFO] Copying server-snippet-0.0.1.xml to /Users/lcr/Downloads/libertyProject/myProject-wlpcfg/target/wlp/usr/servers/LibertyProjectServer/configDropins/defaults/net.wasdev.wlp.starters.rest.server-snippet-0.0.1.xml
[INFO] 
[INFO] --- liberty-maven-plugin:1.1:install-apps (default-install-apps) @ myArtifactId-wlpcfg ---
[INFO] CWWKM2102I: Using installDirectory : /Users/lcr/Downloads/libertyProject/myProject-wlpcfg/target/wlp.
[INFO] CWWKM2102I: Using serverName : LibertyProjectServer.
[INFO] CWWKM2102I: Using serverDirectory : /Users/lcrivas/Downloads/libertyProject/myProject-wlpcfg/target/wlp/usr/servers/LibertyProjectServer.
[INFO] CWWKM2160I: Installing application /Users/lcr/Downloads/libertyProject/myProject-application/target/classes.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] myArtifactId ....................................... SUCCESS [  0.003 s]
[INFO] myArtifactId-application ........................... SUCCESS [ 12.826 s]
[INFO] myArtifactId-wlpcfg ................................ FAILURE [ 47.630 s]
[INFO] myArtifactId-deploy ................................ SKIPPED
[INFO] myArtifactId-localServer ........................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:06 min
[INFO] Finished at: 2016-05-30T20:42:52-04:00
[INFO] Final Memory: 26M/247M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.wasdev.wlp.maven.plugins:liberty-maven-plugin:1.1:install-apps (default-install-apps) on project myArtifactId-wlpcfg: Use a resource collection to copy directories. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :myArtifactId-wlpcfg
lous-mbp-3:libertyProject lcr$

**Comment by katheris** [comment]
This looks like a problem with the Liberty maven plugin, rather than a problem with app accelerator. I will do some investigation.

**Comment by philippe-gregoire** [comment]
I had the same issue which was a problem with my maven configuration, pointing to a non-default maven repository, i.e. the <mirror> section in  %M2_HOME%\conf\settings.xml file had a in-house directory referenced and this repo was not configured to hold or pull some of the artifacts.

Bottom line, use a standard vanilla setting.xml and try again (you can also to a mvn --settings if you don't want to change the global one)

Philippe

**Comment by katheris** [comment]
@lriv Did the above comment solve your problem? If so can we close this issue?

**Comment by katheris** [comment]
Closing as seen no further comments on this issue. Re-open if this is still an issue.
