### ISSUE TITLE
Gradle build support for app accelerator

### ISSUE THREAD

**Issue by katheris** [WASdev/tool.accelerate.core#77]
As a user I want to be able to download a starter app that will build with Gradle.

**Comment by iainduncani** [comment]
Starting work on this on this branch:

https://github.com/WASdev/tool.accelerate.core/tree/addGradleBuild

The initial template of what a Gradle build file would look like to have parity with the maven build is now in place but without the Bluemix support.

**Comment by katheris** [comment]
This work was completed in pull request #118
