### ISSUE TITLE
Identify functions that should be extracted into the Maven plugin.

### ISSUE THREAD

**Issue by katheris** [WASdev/tool.accelerate.core#79]

**Comment by iainduncani** [comment]
I think it would be good to be able to have a packaging type of WAR and the Liberty plugin in the same pom and be able to copy the WAR to WLP. Currently it needs to be listed as a dependency

**Comment by katheris** [comment]
Raised issue in ci.maven: https://github.com/WASdev/ci.maven/issues/106
